version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/git/locationwiki
hooks:
  ApplicationStart:
    - location: /home/ec2-user/app/git/deploy.sh
      timeout: 180
      runas: ec2-user